### ISSUE TITLE
Change the logo

### ISSUE THREAD

**Issue by EmreTech** [Mecha-Karen/acord#49]
Alright, so the logo is not that good. Why? Well, two shades of green that are slightly similar to each other are used in the logo. However, from afar, those shades of green sort of blend together into one shade of green.

Instead of using the same color but a different shade, consider using a color wheel thing to find two colors that fit well together.

Thank you!

**Comment by Tweak4141** [comment]
Your suggestion may be taken into consideration, however, at this time, we have other priorities that need to be dealt with.

**Comment by EmreTech** [comment]
I do understand that changing the logo isn't a big priority for you guys at the moment, but I don't think `invalid` is a valid label for this issue. I think `wontfix` is better.

**Comment by Tweak4141** [comment]
Currently, the issues section is for issues related to the codebase of ACord. Wontfix does not apply, as this may be fixed at a later date.

**Comment by Daftscientist** [comment]
As tweak as clarified, the focus of this project at right now is the core features/code. I will take a look into revising the current logo, taking into account your comments and issues with the current one. 
Thanks for your input, Leo!
